apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentfu
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: slow
  nfs:
    path: /volume1/k8s/
    server: ds209fu
      