---
apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
        version: stable
    spec:
      containers:
      - name: jenkins
        image: jenkins:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name : jenkins
  labels:
    name: jenkins
spec: 
  ports: 
  - port: 8080
    targetPort: 80
  selector:
    name: jenkins
